steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/quizbiblio', '-f', 'QuizBiblio/Dockerfile', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/quizbiblio']

images:
  - 'gcr.io/$PROJECT_ID/quizbiblio'

options:
  logging: CLOUD_LOGGING_ONLY

