using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace QuizBiblio.DataAccess.Utils;

public static class ImageHelper
{
    /// <summary>
    /// Gets the image resized URL in webp format generated by Firebase cloud function extension : Resize Images.
    /// Image is converted to square
    /// </summary>
    /// <param name="filePath">file path to create URL from</param>
    /// <param name="width">width (and height) to include in the URL</param>
    /// <returns>url with following suffix : *_800x800.webp </returns>
    public static string GetResizedUrl(string filePath, int width)
    {
        return filePath.Replace(".png", $"_{width}x{width}.webp");
    }
}
